### ISSUE TITLE
websocket_proxy field missing from config

### ISSUE THREAD

**Issue by lilynet336** [beeper/imessage#24]
I set up mautrix-imessage earlier, and got it fully working. But I noticed that edits and deletes didn't work. So I decided to switch to this bridge, which seems similar enough in terms of config, but when trying to setup the [registration relay](https://github.com/beeper/registration-relay), where it says 
> The bridge and registration providers can then be pointed at the public address of the reverse proxy.
I can't find a way to use a websocket at all. There is an option to *enable* using a websocket, but nowhere to set the URL for one. This isn't exactly a bug report but there's no documentation in the generic Mautrix bridge troubleshooting page for this, and this was my next best option. What am I missing?

**Comment by tulir** [comment]
This bridge doesn't allow configuring a separate websocket proxy. The websocket proxy is also not related to the registration relay in any way. Bridge -> relay connection is http only, no websockets involved, only provider -> relay is websocket (so that the provider on a mac doesn't need a web server). Registration relay address & provider code go in the `nac_validation_*` fields.
